apiVersion: apps/v1
kind: Deployment
metadata: # Define the Deployment Name
  name: coreapi
  labels:
    app: ui-api
spec: # Define the Number of Pods
  replicas: 1
  selector: 
    matchLabels:
      service: coreapi
  template:
    metadata:
      labels:
        app: ui-api
        service: coreapi
    spec:
      containers:
      - name: inmemoryapicontainer
        image: vijaychamp/netinmemoryapi:0.0.3 # version change for each time code changes 
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi" #128 MB
            cpu: "200m" #200 millicpu (.2cpu or 20% of the CPU)
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: inmemoryapiservice
  labels:
    app: ui-api
    service: coreapi
spec:
  type: NodePort #used only for local, for porduction use load balancer
  ports:
    - port: 8080
      targetPort : 80
      protocol: TCP
  selector:
    service: coreapi
    app: ui-api
# kubectl get deployment --show-labels
# kubectl get deployment -l app=nginx    get specific labels
# kubectl scale deployment <<deployment name>> --replicas=5  # sclae deployment pods to 5

# kubectl create .\deployment.yaml --save-config
# kubectl apply -f  .\deployment.yaml

