apiVersion: apps/v1
kind: Deployment
metadata:
  name: coreapi
  labels:
    app: inmemoryapi-core
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coreapi
  template:
    metadata:
      labels:
        app: inmemoryapi-core
        service: coreapi
    spec:
      containers:
      - name: inmemoryapicontainer
        image: vijaychamp/netinmemoryapi:0.0.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi" #128 MB
            cpu: "200m" #200 millicpu (.2cpu or 20% of the CPU)
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: inmemoryapiservice
  labels:
    app: inmemoryapi-core
    service: coreapi
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort : 80
      protocol: TCP
  selector:
    service: coreapi

# kubectl get deployment --show-labels
# kubectl get deployment -l app=nginx    get specific labels
# kubectl scale deployment <<deployment name>> --replicas=5  # sclae deployment pods to 5

# kubectl create .\deployment.yaml --save-config
# kubectl apply -f  .\deployment.yaml

