# Default values for CronJobHelm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: vijaychamp/cronsendmail
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.0.3

restartPolicy: OnFailure
env: dev
schedule: '"* * * * *"'
suspend: true
